### ISSUE TITLE
Security Issue with macOS Catalina 

### ISSUE THREAD

**Issue by ParankushBhardwaj** [supercollider/sc3-plugins#278]
The signed version of 3.10.0 has an issue regarding the file "StkInst.scx". It cannot be opened because "Apple cannot check it for malicious software".

This results in the following consistent error when compiling files that use a SynthDef: "/s_new SynthDef not found".

**Comment by joshpar** [comment]
Are you using the notarized version of SC 3.11?

Can you see if the unsigned versions work as expected with the signed version, please? I think they will, even with the signed version of the main app. We may not need signed binaries.

**Comment by ParankushBhardwaj** [comment]
Yes, I am using 3.11.0 - signed. 

I downloaded the unsigned version of the sc3-plugins, but using that as the extension results in macOS displaying a security alert for every single .scx file. 

The signed version of the sc3-plugins displays the security alert for just the single StkInst.scx file. Again, the security alert is : "StkInst.scx cannot be opened because Apple cannot check it for malicious software".

**Comment by joshpar** [comment]
Thanks! I know why now. That links into another binary that also needs to be signed I think. I’ll try to get an update soon.

**Comment by brianlheim** [comment]
@joshpar any update on this?

**Comment by joshpar** [comment]
I’ll be testing my thoughts on this when we have the build artifacts for me to sign.

Josh

**Comment by iTerentius** [comment]
Yeah, I'm getting the same thing. Mostly I use Linux for this stuff, but work on all day for other things and thought I'd install. I had to force restart in order to get out of the thousand pop-up windows with the same error. Am I missing something or does nobody use these on a Mac?

**Comment by joshpar** [comment]
Please use the unsigned 3.10 version of sc3-plugins for now.

I’m hoping to get this resolved with the 3.11.1 SC release and a new stable release of sc3-plugins. Time hasn’t allowed for this to happen over the past few weeks, though.

Josh

**Comment by telephon** [comment]
till then, the workaround: select the `.scx` file, ctrl-click and open it, select open (despite warning). After this it worked for me.

I find it a real problem that there is no other way to sign code.

**Comment by iTerentius** [comment]
And actually 3.10 unsigned does the same thing for me. I hate the way that Apple has shoe-horned this security stuff in.

**Comment by iTerentius** [comment]
@telephon - So you are going into each folder for all of the plugins and opening from the finder as mentioned? With both solutions @joshpar, even with 3.10 unsigned I still have the same issue. (At this point for testing I'm only adding one plugin, otherwise I end up with a thousand message windows to close). Could be that I'm doing something terribly wrong.

**Comment by telephon** [comment]
> @telephon - So you are going into each folder for all of the plugins and opening from the finder as mentioned?

on my macOS, the files open in xcode and can be closed all at once. Maybe try "open with …" ?

**Comment by iTerentius** [comment]
I thought allowing through privacy settings might work, but no such luck. 
![image](https://user-images.githubusercontent.com/4072714/85957185-e5137000-b950-11ea-8847-057bed75d81e.png)

**Comment by iTerentius** [comment]
Actually, if you "Allow Anyway" on every single one, and hit the cancel button on the pop-up, then when you boot, hit 'open' on each one again, even RC1 does work (and you have to do the same for 3.10). After that I get no warnings and they are all loaded.

**Comment by joshpar** [comment]
We discussed this at our dev meeting yesterday and have a couple more ideas in mind for how to tackle this.

Hopefully a less interactive solution is available soon!

Best,

Josh

**Comment by sfogar** [comment]
Hi,
just to let you know that I purchased a new MacBook pro 13 and I have the same exact problem...

**Comment by joshpar** [comment]
I’m working on this more this week and had some ideas for new approaches from the last dev meeting.
In the mean time, Alessandro, can you also try the 3.10 unsigned plugins if you haven’t already?
Thanks
Josh

/*
Josh Parmenter
www.realizedsound.net/josh
*/

**Comment by sfogar** [comment]
Hi,

tried with the 3.10 unsigned plugins, still no luck.

Perhaps disable Gatekeeper with:

sudo spctl --master-disable

Best

AF

**Comment by joshpar** [comment]
Did that command line work? And, after you get the plugins running once, do you re-enable it?

**Comment by sfogar** [comment]
Joshua,

yes it works very well.

You have to let it so...
The files are checked everytime they are opened.

Best

AF

**Comment by zkamvar** [comment]
Just another data point so I can track this thread: I tried searching for all the scx files in my finder and opening them in a text editor in an attempt to force apple to verify them. When I tried to open them in SC, I still got the popups. They persisted even after I quit the editor, so I had to quit scsynth, which was causing the popups.

**Comment by capital-G** [comment]
I think since there is now a signed version available this has solved.
Another guide that helped me was this one https://cycling74.com/articles/using-unsigned-max-externals-on-mac-os-10-15-catalina so if someone still occurs any problems this could help

```shell
xattr -d -r com.apple.quarantine "/Users/<USERNAME>/Library/Application Support/SuperCollider/Extensions/SC3plugins"
```

**Comment by telephon** [comment]
thanks @capital-G , @joshpar what do you think, should we close?

**Comment by dyfer** [comment]
I think this should be solved with the signed 3.11.x plugins. Please reopen in case this is still an issue.
